---
title: "Austraits analysis"
author: "Dana Lanceman"
date: "2023-10-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 1. Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Get packages}
library(dplyr)
```

```{r Import data}
setwd("C:/Users/z5204897/OneDrive - UNSW/Desktop/PhD/Data_analysis/Data/csv")

austraits_data <- read.csv("austraits_filtered_saltmarshmangroves.csv")
```

```{r Explore data}
aust_spor <- austraits_data %>% subset(taxon_name == "Sporobolus virginicus")
aust_sarc <- austraits_data %>% subset(taxon_name == "Salicornia quinqueflora")
aust_trig <- austraits_data %>% subset(taxon_name == "Triglochin striata")
aust_avic <- austraits_data %>% subset(taxon_name == "Avicennia marina")
aust_aegi <- austraits_data %>% subset(taxon_name == "Aegiceras corniculatum")
aust_rhiz <- austraits_data %>% subset(taxon_name == "Rhizophora mucronata")
aust_brug <- austraits_data %>% subset(taxon_name == "Bruguiera gymnorhiza")

# Check unique `trait_name`s in table for each species
aust_spor %>% pull(trait_name) %>% unique()
```

