---
title: "Mangrove subquadrat traits"
author: "Dana Lanceman"
date: "2023-09-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 1. Set up

```{r Load packages}
#install.packages("readxl")
#install.packages("tidyverse")

library(readxl)
library(tidyverse)
```

```{r Input data}
# set working directory
setwd("C:/Users/z5204897/OneDrive - UNSW/Desktop/PhD/Data_analysis/Project/Functional_traits")

# input mangrove data
manq <- read_excel("Data/Functional_traits_combined_data.xlsx", sheet = "Mangrove_quadrat") %>% 
  arrange(Date, Time) %>% 
  filter(Pneu_dia_mm > 2.5) %>% # excluding unrealistic data point
  mutate(rest_year = case_when(
           Site == "HS" ~ as.numeric("2008"),
           Site == "CC" ~ as.numeric("1990"),
           Site == "CF" ~ as.numeric("1993"),
           Site == "DLW" ~ as.numeric("2014"),
           Site == "CCW" ~ as.numeric("2007"), # don't know the exact year, need to investigate
           Site == "YCW" ~ as.numeric("2018")
         ),
         pneu_h_d = Pneu_ht_mm/Pneu_dia_mm) # add a column for restoration years
# double check with Will years for each
```

# 2. Explore data - Sites, Species, Restoration

```{r Explore subquadrat level variables}
# plot by order of observation
plot(manq$`Seedlings_<30cm_1x1`)
plot(manq$`Seedlings_30-100cm_1x1`)
plot(manq$Propagules_1x1)
plot(manq$Pneu_0.5x0.5)
plot(manq$`Bare_%`)
plot(manq$`Litter_%`)
plot(manq$`Algae_%`)
plot(manq$`Vege_%`)



# plot by site
new_order <- with(manq, reorder(Site, `Seedlings_<30cm_1x1`, median, na.rm=T)) 
boxplot(`Seedlings_<30cm_1x1` ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, `Seedlings_30-100cm_1x1`, median, na.rm=T)) 
boxplot(`Seedlings_30-100cm_1x1` ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, Propagules_1x1, median, na.rm=T)) 
boxplot(Propagules_1x1 ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, Pneu_0.5x0.5, median, na.rm=T)) 
boxplot(Pneu_0.5x0.5 ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, `Bare_%`, median, na.rm=T)) 
boxplot(`Bare_%` ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, `Litter_%`, median, na.rm=T)) 
boxplot(`Litter_%` ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, `Algae_%`, median, na.rm=T)) 
boxplot(`Algae_%` ~ new_order, data = manq) # data insufficient, very zero inflated

new_order <- with(manq, reorder(Site, `Vege_%`, median, na.rm=T)) 
boxplot(`Vege_%` ~ new_order, data = manq) # data insufficient, very zero inflated
```


```{r Explore pneumatophores}
# plot by order recorded
plot(manq$Pneu_ht_mm)
plot(manq$Pneu_dia_mm)
plot(manq$pneu_h_d) 
# there is one extreme h:d ratio, where the diameter has been recorded as 1 mm, which is unrealistic for a pneumatophore - this data point should be removed

# plot by site
new_order <- with(manq, reorder(Site, Pneu_ht_mm, median, na.rm=T)) 
boxplot(Pneu_ht_mm ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, Pneu_dia_mm, median, na.rm=T)) 
boxplot(Pneu_dia_mm ~ new_order, data = manq)

new_order <- with(manq, reorder(Site, pneu_h_d, median, na.rm=T)) 
boxplot(pneu_h_d ~ new_order, data = manq)

# relationships
plot(Pneu_ht_mm ~ Pneu_dia_mm, data = manq)
plot(Pneu_ht_mm ~ Pneu_0.5x0.5, data = manq)
plot(Pneu_dia_mm ~ Pneu_0.5x0.5, data = manq)
plot(pneu_h_d ~ Pneu_0.5x0.5, data = manq)
```


# Explore data - elevation

```{r Elevation}
plot(manq$`Seedlings_<30cm_1x1` ~ manq$Elevation) # nothing clear
plot(manq$`Seedlings_30-100cm_1x1` ~ manq$Elevation) # nothing clear
plot(manq$Propagules_1x1 ~ manq$Elevation) # zero inflated, but seems like low elevations are more likely to have propagules
plot(manq$Pneu_0.5x0.5 ~ manq$Elevation) # potential positive relationship
plot(manq$`Bare_%` ~ manq$Elevation) # nothing clear
plot(manq$`Litter_%` ~ manq$Elevation) # seems like more litter is more likely in higher elevations

plot(manq$Pneu_ht_mm ~ manq$Elevation) # potentially shorter with higher elevations
plot(manq$Pneu_dia_mm ~ manq$Elevation) # nothing clear
plot(manq$pneu_h_d ~ manq$Elevation) # nothing clear
```


# 4. Explore data - by restoration age

```{r}
boxplot(`Seedlings_<30cm_1x1` ~ rest_year, data = manq)
plot(manq$`Seedlings_<30cm_1x1` ~ manq$rest_year) + abline(lm(manq$`Seedlings_<30cm_1x1` ~ manq$rest_year)) # nothing clear

plot(manq$`Seedlings_30-100cm_1x1` ~ manq$rest_year) + abline(lm(manq$`Seedlings_30-100cm_1x1` ~ manq$rest_year)) # nothing clear

plot(manq$Propagules_1x1 ~ manq$rest_year) + abline(lm(manq$Propagules_1x1 ~ manq$rest_year)) # nothing

plot(manq$Pneu_0.5x0.5 ~ manq$rest_year) + abline(lm(manq$Pneu_0.5x0.5 ~ manq$rest_year)) # decreasing trend - older sites have more pneumatophores 

plot(manq$`Bare_%` ~ manq$rest_year) + abline(lm(manq$`Bare_%` ~ manq$rest_year)) # nothing

plot(manq$`Litter_%` ~ manq$rest_year) + abline(lm(manq$`Litter_%` ~ manq$rest_year)) #  nothing


plot(manq$Pneu_ht_mm ~ manq$rest_year) + abline(lm(manq$Pneu_ht_mm ~ manq$rest_year)) # somewhat increasing trend - younger sites have taller pneumatophores

plot(manq$Pneu_dia_mm ~ manq$rest_year) + abline(lm(manq$Pneu_dia_mm ~ manq$rest_year)) # nothing

plot(manq$pneu_h_d ~ manq$rest_year) + abline(lm(manq$pneu_h_d ~ manq$rest_year)) # slight increasing trend
```

