---
title: "Mangrove and saltmarsh elevation visualisation"
author: "Dana Lanceman"
date: "2023-09-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Load packages}
#install.packages("ggplot")

library(readxl)
library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(echo = TRUE)
```

```{r Import data}
setwd("C:/Users/z5204897/OneDrive - UNSW/Desktop/PhD/Data_analysis")

elevdata <- read_excel("Data/xlsx/Functional_traits_RTK_DEM_2023_BlueHeart_Hunter.xlsx", sheet = "boxplot")
elevdata$Category <- factor(elevdata$Category, levels=c("Mangrove_RTK", "Mangrove_DEM", "Saltmarsh_Mangrove", "Saltmarsh_RTK", "Saltmarsh_DEM")) # reorder category
```

```{r}
boxplot(Elevation ~ Category, data = elevdata)
geom_violin(Elevation ~ Category, data = elevdata)

elevdata %>% ggplot( aes(x=Category, y=Elevation, fill=Habitat)) +
  geom_violin(width=1.2) +
  geom_point() +
  geom_hline(yintercept=0.508) +
  annotate("text", x=0.57, y=0.55, label="MHWS") +
  geom_hline(yintercept=0.268)+
  annotate("text", x=0.57, y=0.3, label="MHWN") +
  geom_hline(yintercept=-0.112)+
  annotate("text", x=0.57, y=-0.07, label="MLWN") +
  geom_hline(yintercept=-0.242)+
  annotate("text", x=0.57, y=-0.2, label="MLWS") +
  geom_hline(yintercept=0.128)+
  annotate("text", x=0.5, y=0.17, label="MSL") +
  theme(axis.text = element_text(size = 11),
        axis.title = element_text(size = 12)) +
  xlab("") +
  ylab("Elevation (m AHD)")
```

