---
title: "Saltmarsh community composition"
author: "Dana Lanceman"
date: "2023-10-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 1. Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load packages}
#install.packages("readxl")
#install.packages("tidyverse")
#install.packages("lme4")
#install.packages("MuMIn")

library(readxl)
library(tidyverse)
library(lme4)
library(MuMIn)
```

```{r Input data}
# set working directory
setwd("C:/Users/z5204897/OneDrive - UNSW/Desktop/PhD/Data_analysis/Project/Functional_traits")

# input saltmarsh data
saltc <- read_excel("Data/Functional_traits_combined_data.xlsx", sheet = "Saltmarsh") %>% 
  arrange(Date, Time) %>% 
  mutate(total_stems = Stems * 10000/Quad_length_cm^2, # add column for total stem count per 1m2 for each species to standardise stem counts
         rest_status = case_when(
           Site == "AE" ~ as.numeric("1"),
           Site == "HS" ~ as.numeric("1"),
           Site == "TA" ~ as.numeric("1"),
           Site == "TB" ~ as.numeric("1"),
           Site == "CC" ~ as.numeric("1"),
           Site == "CF" ~ as.numeric("1"),
           Site == "DLW" ~ as.numeric("1"),
           .default = as.numeric("0"), # add a column for restoration status where 1 = restored and 0 = natural
         ),
         rest_year = case_when(
           Site == "AE" ~ as.numeric("2017"),
           Site == "HS" ~ as.numeric("2008"),
           Site == "TA" ~ as.numeric("2007"),
           Site == "TB" ~ as.numeric("2012"),
           Site == "CC" ~ as.numeric("1990"),
           Site == "CF" ~ as.numeric("1993"),
           Site == "DLW" ~ as.numeric("2014")
         ), # add a column for restoration years
         YSR = case_when(
           Site == "AE" ~ as.numeric("6"),
           Site == "HS" ~ as.numeric("15"),
           Site == "TA" ~ as.numeric("16"),
           Site == "TB" ~ as.numeric("11"),
           Site == "CC" ~ as.numeric("33"),
           Site == "CF" ~ as.numeric("30"),
           Site == "DLW" ~ as.numeric("9")
         ))  # add a column for years since restoration
# double check with Will years for each
```


```{r Manipulate dataframe}
# remove irrelevant columns
saltc <- saltc[,c(5,6,7,9,11,12,24,25,27,28,29)]

# convert to wide data with species as columns
saltc_wide <- saltc %>% 
  pivot_wider(names_from = Species, 
              values_from = `Sp_cover_%`,
              values_fn = mean) # there are duplicates for each row. All are identical so the mean will just give us the value they each have.

# create total juncus column to combine 4 juncus columns & total mangrove column to combine 2 mangrove seedling columns
saltc_wide <- saltc_wide %>% 
  mutate(Juncus_tot = rowSums(across((c(25,31,32,33))), na.rm=TRUE),
         mangrove_tot = rowSums(across((c(14,34))), na.rm=TRUE))

# in analysis, need to either include combined columns or their constituents, not both

# replace NAs with zeroes in Species columns
saltc_wide <- saltc_wide %>% 
    mutate_at(c(10:36), ~replace_na(.,0))
```

```{r}
install.packages("writexl")

library(writexl)

# Assuming your dataframe is named 'my_dataframe'
write_xlsx(saltc_wide, "Output/salt_comm_comp2.xlsx")
```

